#!/usr/bin/env bash
# This script configures Nginx for a permanent redirection

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx start

echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/redirect_me

# Create a symbolic link
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

service nginx reload
