#!/usr/bin/env bash
# script that Install and configure HAproxy on your lb-01 server.
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
backend wisepeter-backend
	balance roundrobin
	option forwardfor
	server 100.25.34.61
	server 100.25.180.211

frontend wisepeter-frontend
	bind *:80
	mode http
	default_backend web-backend
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
