#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo service nginx start
