#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely
#receives a sigterm

trap "echo 'I am invincible!!!'" 15

while true 
do
	echo "To infinity and beyond"
	sleep 2
done
