#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while

count=0
while [ $count -le 9 ]
do
	if [ $count -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi

	count=$((count + 1))
done
